name: "Build and cache"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, ubuntu-24.04-arm ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v17
        with:
          name: aleksanderbl
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build
        run: nix build .# --print-build-logs
